# Production environment patches
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: shopmate
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: frontend-service
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: LOG_LEVEL
          value: "info"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: shopmate
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: product-service
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: shopmate
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: cart-service
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: shopmate
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: order-service
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

---
# HPA patches for prod environment
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-service-hpa
  namespace: shopmate
spec:
  minReplicas: 2
  maxReplicas: 10

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: product-service-hpa
  namespace: shopmate
spec:
  minReplicas: 2
  maxReplicas: 10

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart-service-hpa
  namespace: shopmate
spec:
  minReplicas: 2
  maxReplicas: 10

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-service-hpa
  namespace: shopmate
spec:
  minReplicas: 2
  maxReplicas: 10

---
# App Ingress patch (only annotations)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopmate-eks-ingress
  namespace: shopmate
  annotations:
    external-dns.alpha.kubernetes.io/hostname: shopmate-eks.sctp-sandbox.com

