deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    storageClass: gp2-immediate

read:
  replicas: 0

write:
  replicas: 0

backend:
  replicas: 0

test:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false
  serviceMonitor:
    enabled: false

gateway:
  enabled: false

# Disable all cache components
chunksCache:
  enabled: false

resultsCache:
  enabled: false

rulerStorage:
  enabled: false