apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: shopmate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      serviceAccountName: shopmate-service-account
      containers:
      - name: frontend-service
        image: 255945442255.dkr.ecr.ap-southeast-1.amazonaws.com/shopmate-eks:frontend-service
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: shopmate-config
              key: NODE_ENV
        - name: PORT
          value: "3000"
        - name: BASE_URL
          valueFrom:
            configMapKeyRef:
              name: shopmate-config
              key: BASE_URL
        - name: SESSIONS_TABLE
          valueFrom:
            configMapKeyRef:
              name: shopmate-config
              key: SESSIONS_TABLE
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:3001"
        - name: CART_SERVICE_URL
          value: "http://cart-service:3002"
        - name: ORDER_SERVICE_URL
          value: "http://order-service:3003"
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: shopmate-secrets
              key: session-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: shopmate
spec:
  selector:
    app: frontend-service
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP