apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: shopmate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      serviceAccountName: shopmate-service-account
      containers:
      - name: order-service
        image: 255945442255.dkr.ecr.ap-southeast-1.amazonaws.com/shopmate-eks:order-service
        ports:
        - containerPort: 3003
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: shopmate-config
              key: NODE_ENV
        - name: PORT
          value: "3003"
        - name: ORDERS_TABLE
          valueFrom:
            configMapKeyRef:
              name: shopmate-config
              key: ORDERS_TABLE
        - name: BASE_URL
          valueFrom:
            configMapKeyRef:
              name: shopmate-config
              key: BASE_URL
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:3001"
        - name: CART_SERVICE_URL
          value: "http://cart-service:3002"
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: shopmate-config
              key: AWS_REGION
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: shopmate
spec:
  selector:
    app: order-service
  ports:
  - port: 3003
    targetPort: 3003
  type: ClusterIP