apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: shopmate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      serviceAccountName: shopmate-service-account
      containers:
      - name: product-service
        image: 255945442255.dkr.ecr.ap-southeast-1.amazonaws.com/shopmate-eks:product-service
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: shopmate-config
              key: NODE_ENV
        - name: PORT
          value: "3001"
        - name: PRODUCTS_TABLE
          valueFrom:
            configMapKeyRef:
              name: shopmate-config
              key: PRODUCTS_TABLE
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: shopmate-config
              key: AWS_REGION
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: shopmate
spec:
  selector:
    app: product-service
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP