apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shopmate-session-secret
  namespace: shopmate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager-cluster
    kind: ClusterSecretStore
  target:
    name: shopmate-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        session-secret: "{{ .sessionSecret }}"
  data:
  - secretKey: sessionSecret
    remoteRef:
      key: PLACEHOLDER_AWS_SECRET_NAME
      property: session-secret